{"name": "test_get_order_whith_wrong_track_id", "status": "passed", "steps": [{"name": "Получаем ошибку при попытке получит заказ по несуществующему номера", "status": "passed", "steps": [{"name": "Создаем рандомный номер заказа", "status": "passed", "start": 1749721972357, "stop": 1749721972357}], "start": 1749721972357, "stop": 1749721972769}], "start": 1749721972357, "stop": 1749721972769, "uuid": "ffa37568-e655-4777-897e-57a362d5ce64", "historyId": "7300437e1a9800b3d52332e0d224aefd", "testCaseId": "7300437e1a9800b3d52332e0d224aefd", "fullName": "tests.test_get_order_by_track.TestGetOrderById#test_get_order_whith_wrong_track_id", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_order_by_track"}, {"name": "subSuite", "value": "TestGetOrderById"}, {"name": "host", "value": "MacBook-Pro.local"}, {"name": "thread", "value": "76481-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_order_by_track"}]}