{"name": "test_get_order_whith_wrong_track_id", "status": "passed", "steps": [{"name": "Получаем ошибку при попытке получит заказ по несуществующему номера", "status": "passed", "steps": [{"name": "Создаем рандомный номер заказа", "status": "passed", "start": 1749547373520, "stop": 1749547373520}], "start": 1749547373520, "stop": 1749547373891}], "start": 1749547373520, "stop": 1749547373892, "uuid": "34233eed-3dcb-446f-9275-966f64a1ec78", "historyId": "d047e99431ceea71ae5646c9e5f66733", "testCaseId": "d047e99431ceea71ae5646c9e5f66733", "fullName": "Test.test_get_order_by_track.TestGetOrderById#test_get_order_whith_wrong_track_id", "labels": [{"name": "parentSuite", "value": "Test"}, {"name": "suite", "value": "test_get_order_by_track"}, {"name": "subSuite", "value": "TestGetOrderById"}, {"name": "host", "value": "MacBook-Pro.local"}, {"name": "thread", "value": "45635-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Test.test_get_order_by_track"}]}